lib/snownix_web/router.ex
defmodule SnownixWeb.Router do
  use SnownixWeb, :router

  import SnownixWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SnownixWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug SnownixWeb.Plugs.SetLocale
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  ## Liveview routes
  live_session :default, on_mount: {SnownixWeb.InitAssigns, :user} do
    scope "/", SnownixWeb do
      pipe_through [:browser]

      live "/", IndexLive.Index, :index

      scope "/posts" do
        live "/", PostLive.List, :list
        live "/:slug", PostLive.Read, :read
      end

      live "/profile/:username", AccountLive.Profile, :index

      scope "/account" do
        live "/confirm", AuthLive.Reconfirm, :reconfirm
        live "/confirm/:token", AuthLive.Confirm, :confirm
      end

      scope "/" do
        pipe_through [:require_authenticated_user]

        live "/account/settings", AccountLive.Settings, :settings

        live "/new-post", PostLive.New, :new
        live "/edit-post/:id", PostLive.Edit, :edit
      end

      scope "/admin" do
        pipe_through [:require_authenticated_user]
        live "/menus", MenuLive.Index, :index
        live "/menus/new", MenuLive.Index, :new
        live "/menus/:id/edit", MenuLive.Index, :edit

        live "/menus/:id", MenuLive.Show, :show
        live "/menus/:id/show/edit", MenuLive.Show, :edit

        live "/posts", PostLive.Index, :index
        live "/posts/new", PostLive.Index, :new
        live "/posts/:id/edit", PostLive.Index, :edit

        live "/posts/:id", PostLive.Show, :show
        live "/posts/:id/show/edit", PostLive.Show, :edit

        live "/categories", CategoryLive.Index, :index
        live "/categories/new", CategoryLive.Index, :new
        live "/categories/:id/edit", CategoryLive.Index, :edit

        live "/categories/:id", CategoryLive.Show, :show
        live "/categories/:id/show/edit", CategoryLive.Show, :edit
      end

      scope "/auth" do
        pipe_through [:redirect_if_user_is_authenticated]

        live "/login", AuthLive.Login, :login
        live "/register", AuthLive.Register, :register
        live "/forgot-password", AuthLive.ForgotPassword, :forgot
        live "/reset-password/:token", AuthLive.ResetPassword, :reset
      end
    end
  end

  ## Controllers
  scope "/auth", SnownixWeb do
    pipe_through [:browser]

    delete "/logout", UserSessionController, :delete
  end

  scope "/auth", SnownixWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]
    post "/login", UserSessionController, :create
    get "/github/callbacks/register", Providers.GithubRegisterController, :create
    get "/github/callbacks/login", Providers.GithubLoginController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", SnownixWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL  which you should anyway.
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: SnownixWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/snownix_web/live/account_live/profile.ex
defmodule SnownixWeb.AccountLive.Profile do
  use SnownixWeb, :live_view

  alias Snownix.Accounts
  alias Snownix.{Posts, Posts.Post, Pagination, Repo}

  def mount(%{"username" => username}, _session, socket) do
    {:ok,
     socket
     |> assign_profile(username)
     |> assign_posts()
     |> assign_meta_tags()}
  end

  defp assign_meta_tags(socket) do
    %{username: username} = socket.assigns

    socket
    |> put_meta_tags(%{
      page_title: gettext("%{username} Profile", username: username),
      page_desc: gettext("User %{username} posts", username: username),
      page_keywords: "#{username},blog,articles,posts,snownix,phoenix,self hosted,open source"
    })
  end

  defp assign_profile(socket, username) do
    profile = Accounts.get_user_by_username!(username)

    socket
    |> assign(:username, username)
    |> assign(:profile, profile)
  end

  def assign_posts(socket) do
    socket
    |> assign(:pagination, [])
    |> load_more(page: 1)
  end

  def load_more(socket, page: page) when page < 0, do: socket

  def load_more(socket, page: page) do
    pagination =
      Post
      |> Posts.by_user(socket.assigns.username)
      |> Posts.order_posts()
      |> Pagination.page(page, per_page: 6)

    pagination = %{
      pagination
      | items:
          pagination.items
          |> Repo.preload(:author)
          |> Repo.preload(:categories)
    }

    socket |> assign(:pagination, pagination)
  end
end

lib/snownix_web/live/account_live/settings.ex
defmodule SnownixWeb.AccountLive.Settings do
  use SnownixWeb, :live_view

  alias Snownix.Accounts
  alias Snownix.Avatar, warn: false

  @tabs ["My Details", "Security", "Notifications"]
  def mount(_, _, socket) do
    {:ok,
     socket
     |> assign(:tabs, @tabs)
     |> allow_upload(:avatar,
       accept: ~w(.jpg .jpeg .png .gif .txt),
       max_entries: 1,
       max_file_size: 2_000_000,
       auto_upload: true,
       progress: &handle_progress/3
     )
     |> assign(:tab, select_tab())
     |> assign(:changeset, socket.assigns.current_user |> Accounts.user_changeset(%{}))}
  end

  def handle_event("switch-tab", %{"tab" => tab}, socket) do
    {:noreply, socket |> assign(:tab, select_tab(tab))}
  end

  def handle_event("details-validate", %{"user" => user_params}, socket) do
    {:noreply,
     socket
     |> clear_flash()
     |> assign(
       :changeset,
       socket.assigns.current_user
       |> Accounts.user_changeset(user_params)
       |> Map.put(:action, :validate)
     )}
  end

  def handle_event("details-save", %{"user" => user_params}, socket) do
    user = socket.assigns.current_user

    %{"current_password" => password} = user_params

    case Accounts.update_user(user, password, user_params) do
      {:ok, user} ->
        {:noreply,
         socket
         |> assign(:current_user, user)
         |> assign(:changeset, Accounts.user_changeset(user, user_params))
         |> put_flash(:success, gettext("Account information updated successfully."))}

      {:error, changeset} ->
        {:noreply, socket |> assign(:changeset, changeset)}
    end
  end

  # Avatar
  def handle_event("validate", _, socket), do: {:noreply, socket}

  def handle_event("delete-avatar", _, socket) do
    current_user = socket.assigns.current_user

    if !is_nil(current_user.avatar) do
      Snownix.Uploaders.AvatarUploader.delete({current_user.avatar, current_user})
    end

    case Accounts.update_user_avatar(current_user, nil) do
      {:ok, user} ->
        {:noreply, socket |> assign(:current_user, user)}

      _ ->
        {:noreply, socket}
    end
  end

  defp handle_progress(:avatar, entry, socket) do
    if entry.done? do
      current_user = socket.assigns.current_user

      consume_uploaded_entries(socket, :avatar, fn meta, entry ->
        {:ok, user} =
          Accounts.update_user_avatar(current_user, %Plug.Upload{
            content_type: entry.client_type,
            filename: entry.client_name,
            path: meta.path
          })

        {:ok, Snownix.Uploaders.AvatarUploader.url({user.avatar, user}, :original)}
      end)

      {:noreply, socket}
    else
      {:noreply, socket}
    end
  end

  # Tabs
  defp select_tab(tab \\ nil) do
    Enum.find(@tabs, List.first(@tabs), &(&1 == tab))
  end

  def is_active_tab(current, tab) do
    current == tab
  end

  # Upload messages
  defp error_to_string(:too_large), do: gettext("File size is too large, max allowed 2MB.")
  defp error_to_string(:too_many_files), do: gettext("You have selected too many files.")

  defp error_to_string(:not_accepted),
    do: gettext("You have selected an unacceptable file type, only images are accepted.")
end

lib/snownix_web/live/auth_live/confirm.ex
defmodule SnownixWeb.AuthLive.Confirm do
  use SnownixWeb, :live_view

  alias Snownix.Accounts

  def mount(%{"token" => token}, _, socket) do
    {
      :ok,
      socket
      |> assign(:page_title, gettext("Confirm"))
      |> get_user_by_confirm_account_token(token)
    }
  end

  defp get_user_by_confirm_account_token(socket, token) do
    if user = Accounts.get_user_by_confirm_account_token(token) do
      socket
      |> assign(:user, user)
      |> assign(:token, token)
      |> assign(changeset: Accounts.user_email_changeset(%Accounts.User{}))
    else
      socket
      |> put_flash(:error, "Confirm link is invalid or it has expired.")
      |> redirect(to: Routes.auth_login_path(socket, :login))
    end
  end

  def handle_event("validate", %{"user" => user_params}, socket) do
    changeset =
      %Accounts.User{}
      |> Accounts.user_email_changeset(user_params)
      |> Map.put(:action, :validate)

    {:noreply, socket |> assign(:changeset, changeset)}
  end

  def handle_event("update", %{"user" => user_params}, socket) do
    with %{"email" => email} <- user_params do
      case Accounts.confirm_user(socket.assigns.token, email) do
        {:ok, _} ->
          {:noreply,
           socket
           |> put_flash(:info, "Account confirmed successfully.")
           |> redirect(to: Routes.auth_login_path(socket, :login))}

        :error ->
          # If there is a current user and the account was already confirmed,
          # then odds are that the confirmation link was already visited, either
          # by some automation or by the user themselves, so we redirect without
          # a warning message.
          case socket.assigns do
            %{current_user: %{confirmed_at: confirmed_at}} when not is_nil(confirmed_at) ->
              {:noreply,
               socket
               |> put_flash(:error, "Account has already been confirmed")
               |> redirect(to: Routes.auth_login_path(socket, :login))}

            %{} ->
              {:noreply,
               socket
               |> put_flash(:error, "Account confirmation link is invalid or it has expired.")
               |> redirect(to: Routes.auth_login_path(socket, :login))}
          end
      end
    end
  end
end

lib/snownix_web/live/auth_live/forgot_password.ex
defmodule SnownixWeb.AuthLive.ForgotPassword do
  use SnownixWeb, :live_view

  alias Snownix.Accounts

  def mount(_, _, socket) do
    {
      :ok,
      socket
      |> assign(:page_title, gettext("Forgot Password"))
      |> assign(
        :changeset,
        Accounts.user_email_changeset(%Accounts.User{})
      )
    }
  end

  def handle_event("validate", %{"user" => user_params}, socket) do
    changeset =
      %Accounts.User{}
      |> Accounts.user_email_changeset(user_params)
      |> Map.put(:action, :validate)

    {:noreply, socket |> assign(:changeset, changeset)}
  end

  def handle_event("update", %{"user" => user_params}, socket) do
    %{"email" => email} = user_params

    if user = Accounts.get_user_by_email(email) do
      Accounts.deliver_user_reset_password_instructions(
        user,
        &Routes.auth_reset_password_url(socket, :reset, &1)
      )
    end

    {:noreply,
     socket
     |> put_flash(
       :info,
       gettext(
         "If your email is in our system, you will receive instructions to reset your password shortly."
       )
     )
     |> redirect(to: Routes.auth_login_path(socket, :login))}
  end
end

lib/snownix_web/live/auth_live/login.ex
defmodule SnownixWeb.AuthLive.Login do
  use SnownixWeb, :live_view

  alias Snownix.Accounts
  alias Snownix.Providers.Github

  def mount(_, _, socket) do
    {:ok,
     socket
     |> assign(:trigger_submit, false)
     |> assign(:changeset, Accounts.user_login_changeset(%Accounts.User{}))
     |> assign(:page_title, gettext("Sign in"))}
  end

  def handle_event("validate", %{"user" => user_params}, socket) do
    changeset =
      %Accounts.User{}
      |> Accounts.user_login_changeset(user_params)
      |> Map.put(:action, :validate)

    {:noreply, socket |> clear_flash() |> assign(:changeset, changeset)}
  end

  def handle_event("create", %{"user" => user_params}, socket) do
    %{"email" => email, "password" => password} = user_params

    if user = Accounts.get_user_by_email_and_password(email, password) do
      {:noreply,
       socket
       |> put_flash(:info, gettext("Welcome back %{username}!", username: user.username))
       |> assign(:trigger_submit, true)}
    else
      {:noreply,
       socket
       # In order to prevent user enumeration attacks, don't disclose whether the email is registered.
       |> put_flash(:error, gettext("Invalid email or password"))}
    end
  end
end

lib/snownix_web/live/auth_live/reconfirm.ex
defmodule SnownixWeb.AuthLive.Reconfirm do
  use SnownixWeb, :live_view

  alias Snownix.Accounts

  def mount(_, _, socket) do
    {
      :ok,
      socket
      |> assign(:page_title, gettext("Resend Confirmation Instructions"))
      |> assign(
        :changeset,
        Accounts.user_email_changeset(%Accounts.User{})
      )
    }
  end

  def handle_event("validate", %{"user" => user_params}, socket) do
    changeset =
      %Accounts.User{}
      |> Accounts.user_email_changeset(user_params)
      |> Map.put(:action, :validate)

    {:noreply, socket |> assign(:changeset, changeset)}
  end

  def handle_event("update", %{"user" => user_params}, socket) do
    %{"email" => email} = user_params

    if user = Accounts.get_user_by_email(email) do
      Accounts.deliver_user_confirmation_instructions(
        user,
        &Routes.auth_confirm_url(socket, :confirm, &1)
      )
    end

    {:noreply,
     socket
     |> put_flash(
       :info,
       gettext(
         "If your email is in our system and it has not been confirmed yet, " <>
           "you will receive an email with instructions shortly"
       )
     )
     |> redirect(to: Routes.auth_login_path(socket, :login))}
  end
end

lib/snownix_web/live/auth_live/register.ex
defmodule SnownixWeb.AuthLive.Register do
  use SnownixWeb, :live_view

  alias Snownix.Accounts
  alias Snownix.Providers.Github

  def mount(_, _, socket) do
    {:ok,
     socket
     |> assign(:changeset, Accounts.user_register_changeset(%Accounts.User{}))
     |> assign(:page_title, gettext("Sign up"))}
  end

  def handle_event("validate", %{"user" => user_params}, socket) do
    changeset =
      %Accounts.User{}
      |> Accounts.user_register_changeset(user_params, uniq_email: false)
      |> Map.put(:action, :validate)

    {:noreply, socket |> assign(:changeset, changeset)}
  end

  def handle_event("create", %{"user" => user_params}, socket) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.auth_confirm_url(socket, :confirm, &1)
          )

        {:noreply,
         socket
         |> put_flash(
           :info,
           gettext(
             "Registration completed successfully. please check your email to verify your account."
           )
         )
         |> redirect(to: Routes.auth_login_path(socket, :login))}

      {:error, changeset} ->
        {:noreply,
         socket
         |> assign(:changeset, changeset)}
    end
  end
end

lib/snownix_web/live/auth_live/reset_password.ex
defmodule SnownixWeb.AuthLive.ResetPassword do
  use SnownixWeb, :live_view

  alias Snownix.Accounts

  def mount(%{"token" => token}, _, socket) do
    {
      :ok,
      socket
      |> assign(:page_title, gettext("Reset Password"))
      |> get_user_by_reset_password_token(token)
    }
  end

  defp get_user_by_reset_password_token(socket, token) do
    if user = Accounts.get_user_by_reset_password_token(token) do
      socket
      |> assign(:user, user)
      |> assign(:token, token)
      |> assign(:changeset, Accounts.user_password_changeset(%Accounts.User{}))
    else
      socket
      |> put_flash(:error, "Reset password link is invalid or it has expired.")
      |> redirect(to: Routes.auth_login_path(socket, :login))
    end
  end

  def handle_event("validate", %{"user" => user_params}, socket) do
    changeset =
      %Accounts.User{}
      |> Accounts.user_password_with_email_changeset(user_params)
      |> Map.put(:action, :validate)

    {:noreply, socket |> assign(:changeset, changeset)}
  end

  def handle_event("update", %{"user" => user_params}, socket) do
    with %{"email" => email} <- user_params do
      if socket.assigns.user.email === email do
        case Accounts.reset_user_password(socket.assigns.user, user_params) do
          {:ok, _} ->
            {:noreply,
             socket
             |> put_flash(:info, "Password reset successfully.")
             |> redirect(to: Routes.auth_login_path(socket, :login))}

          {:error, changeset} ->
            {:noreply,
             socket
             |> assign(changeset: changeset)}
        end
      else
        {:noreply, socket |> put_flash(:error, gettext("Wrong information"))}
      end
    end
  end
end

lib/snownix_web/live/post_live/components/post_grid_component.ex
defmodule SnownixWeb.PostLive.Components.PostGridComponent do
  use SnownixWeb, :live_component
end

lib/snownix_web/live/shared_live/alerts_component.html.heex
<div class="alerts" phx-hook="Flash">
    <%= if message = live_flash(@flash, :info) do %>
        <div class="alert alert-info">
            <svg class="inline flex-shrink-0 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
            <%= message %>
        </div>
    <% end %>
    <%= if message = live_flash(@flash, :error) do %>
        <div class="alert alert-danger">
            <svg class="inline flex-shrink-0 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
            <%= message %>
        </div>
    <% end %>
    <%= if message = live_flash(@flash, :success) do %>
        <div class="alert alert-success">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="inline flex-shrink-0 w-5 h-5" fill="currentColor"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M9 16.2L4.8 12l-1.4 1.4L9 19 21 7l-1.4-1.4L9 16.2z"/></svg>
            <%= message %>
        </div>
    <% end %>
</div>

lib/snownix_web/live/shared_live/footer_component.html.heex
<section class="bg-white">
    <div class="container flex flex-col items-center px-4 py-8 mx-auto space-y-8 overflow-hidden sm:px-6 lg:px-8">
        <form phx-hook="Lang" id="select-lang">
            <select name="lang" id="lang">
                <%= for {title, val} <- get_langs() do %>
                <option value={val} selected={@locale == val}><%=title%></option>
                <% end %>
            </select>
        </form>
        <div class="flex justify-center mt-8 space-x-6">
            <a href="#" class="text-gray-500 hover:text-gray-500">
                <span class="sr-only">Instagram</span>
                <%= render SnownixWeb.IconsView, "instagram.svg", %{} %>
            </a>
            <a href="#" class="text-gray-500 hover:text-gray-500">
                <span class="sr-only">Twitter</span>
                <%= render SnownixWeb.IconsView, "twitter.svg", %{} %>
            </a>
            <a href="#" class="text-gray-500 hover:text-gray-500">
                <span class="sr-only">GitHub</span>
                <%= render SnownixWeb.IconsView, "github.svg", %{} %>
            </a>
            <a href="#" class="text-gray-500 hover:text-gray-500">
                <span class="sr-only">Dribbble</span>
                <%= render SnownixWeb.IconsView, "dribbble.svg", %{} %>
            </a>
            <a href="#" class="text-gray-500 hover:text-gray-500">
                <span class="sr-only">Behance</span>
                <%= render SnownixWeb.IconsView, "behance.svg", %{} %>
            </a>
        </div>
        <p class="mt-8 text-base leading-6 text-center text-gray-500">© <%= Date.utc_today().year %> <%= assigns[:app_name] || "Snownix" %>. All rights reserved.</p>
    </div>
</section>

lib/snownix_web/live/shared_live/header_component.html.heex
<section class="header relative text-gray-700  body-font">
    <div class="flex flex-col flex-wrap items-center justify-between py-4 mx-auto md:flex-row container">
        <%= live_patch to: "/", class: "logo relative  z-10" do %>
            Snownix
            <span class="text-primary">.</span>
        <% end %>
        <nav class="top-0 left-0 z-0 flex items-center justify-center w-full h-full -ml-0 space-x-5 text-base md:-ml-5 md:absolute py-4 md:py-0">
            <%= for menu <- list_menu() do %>
                <div data-menu data-hover>
                   <div class="flex items-end">
                        <%= if menu.item.newtab do %>
                            <%= link menu.item.title, to: menu.item.link, target: "_blank" %>
                        <% else %>
                            <%= live_redirect menu.item.title, to: menu.item.link %>
                        <% end %>
                        <%= if length(menu.sub) > 0 do %>
                            <svg class="text-gray-400 h-5 w-5 group-hover:text-gray-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                            </svg>
                        <% end %>
                   </div>
                    <%= if length(menu.sub) > 0 do %>
                        <ul data-menu-dropdown class="w-44 min-w-max text-base list-none bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600 left-0 top-4">
                            <%= for sub <- menu.sub do %>
                                <li class="p-3">
                                    <%= if sub.item.newtab do %>
                                        <%= link sub.item.title, to: sub.item.link, target: "_blank" %>
                                    <% else %>
                                        <%= live_redirect sub.item.title, to: sub.item.link %>
                                    <% end %>
                                </li>
                            <% end %>
                        </ul>
                    <% end %>
                </div>
            <% end %>
        </nav>
        <div class="flex flex-col space-y-3 md:space-y-0 md:flex-row relative  items-center space-x-3 md:ml-5 lg:justify-end">
            <div class="auth__menu">
                <%= if @current_user do %>
                    <.live_component 
                        id="user-menu"
                        current_user={@current_user}
                        module={SnownixWeb.SharedLive.UserMenuComponent}/>
                <% else %>
                    <%= live_redirect gettext("Sign in"), to: Routes.auth_login_path(@socket, :login) , class: "btn"%>
                    <%= live_redirect gettext("Sign up"), to: Routes.auth_register_path(@socket, :register), class: "btn primary"  %>
                <% end %>
            </div>
        </div>
    </div>
</section>

lib/snownix_web/live/shared_live/user_menu_component.html.heex
<div class="flex items-center">
<div>
    <%= live_redirect gettext("New Post"), to: Routes.post_new_path(@socket, :new), class: "btn primary"%>
</div>
<div data-menu>
    <button 
        class="light space-x-2" type="button">
        <span><%= @current_user.fullname %></span>
        <img class="w-10 h-10 avatar shadow-sm" src={get_user_avatar(@current_user)}>
    </button>

    <!-- Dropdown menu -->
    <div data-menu-dropdown class="z-10  text-base list-none bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600">
        <div class="py-3 px-4 text-gray-900 dark:text-white">
        <span class="block text-sm"><%= @current_user.fullname %></span>
        <span class="block text-sm font-medium truncat"><%= @current_user.email %></span>
        </div>
        <ul class="py-1 w-full" >
            <li>
                <%= live_redirect gettext("Profile"), to: Routes.account_profile_path(SnownixWeb.Endpoint, :index, @current_user.username), 
                class: "block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" %>
            </li>
            <li>
                <%= live_redirect gettext("Settings"), to: Routes.account_settings_path(SnownixWeb.Endpoint, :settings), 
                class: "block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" %>
            </li>
        </ul>
        <div class="py-1 w-full">
            <%= link gettext("Log out"), to: Routes.user_session_path(SnownixWeb.Endpoint, :delete), 
            class: "block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white", 
            method: :delete %>
        </div>
    </div>
</div>
</div>