lib/snownix_web/router.ex
defmodule SnownixWeb.Router do
  use SnownixWeb, :router

  import SnownixWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SnownixWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug SnownixWeb.Plugs.SetLocale
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  ## Liveview routes
  live_session :default, on_mount: {SnownixWeb.InitAssigns, :user} do
    scope "/", SnownixWeb do
      pipe_through [:browser]

      live "/", IndexLive.Index, :index

      scope "/posts" do
        live "/", PostLive.List, :list
        live "/:slug", PostLive.Read, :read
      end

      live "/profile/:username", AccountLive.Profile, :index

      scope "/account" do
        live "/confirm", AuthLive.Reconfirm, :reconfirm
        live "/confirm/:token", AuthLive.Confirm, :confirm
      end

      scope "/" do
        pipe_through [:require_authenticated_user]

        live "/account/settings", AccountLive.Settings, :settings

        live "/new-post", PostLive.New, :new
        live "/edit-post/:id", PostLive.Edit, :edit
      end

      scope "/admin" do
        pipe_through [:require_authenticated_user]
        live "/menus", MenuLive.Index, :index
        live "/menus/new", MenuLive.Index, :new
        live "/menus/:id/edit", MenuLive.Index, :edit

        live "/menus/:id", MenuLive.Show, :show
        live "/menus/:id/show/edit", MenuLive.Show, :edit

        live "/posts", PostLive.Index, :index
        live "/posts/new", PostLive.Index, :new
        live "/posts/:id/edit", PostLive.Index, :edit

        live "/posts/:id", PostLive.Show, :show
        live "/posts/:id/show/edit", PostLive.Show, :edit

        live "/categories", CategoryLive.Index, :index
        live "/categories/new", CategoryLive.Index, :new
        live "/categories/:id/edit", CategoryLive.Index, :edit

        live "/categories/:id", CategoryLive.Show, :show
        live "/categories/:id/show/edit", CategoryLive.Show, :edit
      end

      scope "/auth" do
        pipe_through [:redirect_if_user_is_authenticated]

        live "/login", AuthLive.Login, :login
        live "/register", AuthLive.Register, :register
        live "/forgot-password", AuthLive.ForgotPassword, :forgot
        live "/reset-password/:token", AuthLive.ResetPassword, :reset
      end
    end
  end

  ## Controllers
  scope "/auth", SnownixWeb do
    pipe_through [:browser]

    delete "/logout", UserSessionController, :delete
  end

  scope "/auth", SnownixWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]
    post "/login", UserSessionController, :create
    get "/github/callbacks/register", Providers.GithubRegisterController, :create
    get "/github/callbacks/login", Providers.GithubLoginController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", SnownixWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL  which you should anyway.
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: SnownixWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/snownix_web/live/account_live/profile.ex
defmodule SnownixWeb.AccountLive.Profile do
  use SnownixWeb, :live_view

  alias Snownix.Accounts
  alias Snownix.{Posts, Posts.Post, Pagination, Repo}

  def mount(%{"username" => username}, _session, socket) do
    {:ok,
     socket
     |> assign_profile(username)
     |> assign_posts()
     |> assign_meta_tags()}
  end

  defp assign_meta_tags(socket) do
    %{username: username} = socket.assigns

    socket
    |> put_meta_tags(%{
      page_title: gettext("%{username} Profile", username: username),
      page_desc: gettext("User %{username} posts", username: username),
      page_keywords: "#{username},blog,articles,posts,snownix,phoenix,self hosted,open source"
    })
  end

  defp assign_profile(socket, username) do
    profile = Accounts.get_user_by_username!(username)

    socket
    |> assign(:username, username)
    |> assign(:profile, profile)
  end

  def assign_posts(socket) do
    socket
    |> assign(:pagination, [])
    |> load_more(page: 1)
  end

  def load_more(socket, page: page) when page < 0, do: socket

  def load_more(socket, page: page) do
    pagination =
      Post
      |> Posts.by_user(socket.assigns.username)
      |> Posts.order_posts()
      |> Pagination.page(page, per_page: 6)

    pagination = %{
      pagination
      | items:
          pagination.items
          |> Repo.preload(:author)
          |> Repo.preload(:categories)
    }

    socket |> assign(:pagination, pagination)
  end
end

lib/snownix_web/live/account_live/settings.ex
defmodule SnownixWeb.AccountLive.Settings do
  use SnownixWeb, :live_view

  alias Snownix.Accounts
  alias Snownix.Avatar, warn: false

  @tabs ["My Details", "Security", "Notifications"]
  def mount(_, _, socket) do
    {:ok,
     socket
     |> assign(:tabs, @tabs)
     |> allow_upload(:avatar,
       accept: ~w(.jpg .jpeg .png .gif .txt),
       max_entries: 1,
       max_file_size: 2_000_000,
       auto_upload: true,
       progress: &handle_progress/3
     )
     |> assign(:tab, select_tab())
     |> assign(:changeset, socket.assigns.current_user |> Accounts.user_changeset(%{}))}
  end

  def handle_event("switch-tab", %{"tab" => tab}, socket) do
    {:noreply, socket |> assign(:tab, select_tab(tab))}
  end

  def handle_event("details-validate", %{"user" => user_params}, socket) do
    {:noreply,
     socket
     |> clear_flash()
     |> assign(
       :changeset,
       socket.assigns.current_user
       |> Accounts.user_changeset(user_params)
       |> Map.put(:action, :validate)
     )}
  end

  def handle_event("details-save", %{"user" => user_params}, socket) do
    user = socket.assigns.current_user

    %{"current_password" => password} = user_params

    case Accounts.update_user(user, password, user_params) do
      {:ok, user} ->
        {:noreply,
         socket
         |> assign(:current_user, user)
         |> assign(:changeset, Accounts.user_changeset(user, user_params))
         |> put_flash(:success, gettext("Account information updated successfully."))}

      {:error, changeset} ->
        {:noreply, socket |> assign(:changeset, changeset)}
    end
  end

  # Avatar
  def handle_event("validate", _, socket), do: {:noreply, socket}

  def handle_event("delete-avatar", _, socket) do
    current_user = socket.assigns.current_user

    if !is_nil(current_user.avatar) do
      Snownix.Uploaders.AvatarUploader.delete({current_user.avatar, current_user})
    end

    case Accounts.update_user_avatar(current_user, nil) do
      {:ok, user} ->
        {:noreply, socket |> assign(:current_user, user)}

      _ ->
        {:noreply, socket}
    end
  end

  defp handle_progress(:avatar, entry, socket) do
    if entry.done? do
      current_user = socket.assigns.current_user

      consume_uploaded_entries(socket, :avatar, fn meta, entry ->
        {:ok, user} =
          Accounts.update_user_avatar(current_user, %Plug.Upload{
            content_type: entry.client_type,
            filename: entry.client_name,
            path: meta.path
          })

        {:ok, Snownix.Uploaders.AvatarUploader.url({user.avatar, user}, :original)}
      end)

      {:noreply, socket}
    else
      {:noreply, socket}
    end
  end

  # Tabs
  defp select_tab(tab \\ nil) do
    Enum.find(@tabs, List.first(@tabs), &(&1 == tab))
  end

  def is_active_tab(current, tab) do
    current == tab
  end

  # Upload messages
  defp error_to_string(:too_large), do: gettext("File size is too large, max allowed 2MB.")
  defp error_to_string(:too_many_files), do: gettext("You have selected too many files.")

  defp error_to_string(:not_accepted),
    do: gettext("You have selected an unacceptable file type, only images are accepted.")
end

lib/snownix_web/live/auth_live/confirm.ex
defmodule SnownixWeb.AuthLive.Confirm do
  use SnownixWeb, :live_view

  alias Snownix.Accounts

  def mount(%{"token" => token}, _, socket) do
    {
      :ok,
      socket
      |> assign(:page_title, gettext("Confirm"))
      |> get_user_by_confirm_account_token(token)
    }
  end

  defp get_user_by_confirm_account_token(socket, token) do
    if user = Accounts.get_user_by_confirm_account_token(token) do
      socket
      |> assign(:user, user)
      |> assign(:token, token)
      |> assign(changeset: Accounts.user_email_changeset(%Accounts.User{}))
    else
      socket
      |> put_flash(:error, "Confirm link is invalid or it has expired.")
      |> redirect(to: Routes.auth_login_path(socket, :login))
    end
  end

  def handle_event("validate", %{"user" => user_params}, socket) do
    changeset =
      %Accounts.User{}
      |> Accounts.user_email_changeset(user_params)
      |> Map.put(:action, :validate)

    {:noreply, socket |> assign(:changeset, changeset)}
  end

  def handle_event("update", %{"user" => user_params}, socket) do
    with %{"email" => email} <- user_params do
      case Accounts.confirm_user(socket.assigns.token, email) do
        {:ok, _} ->
          {:noreply,
           socket
           |> put_flash(:info, "Account confirmed successfully.")
           |> redirect(to: Routes.auth_login_path(socket, :login))}

        :error ->
          # If there is a current user and the account was already confirmed,
          # then odds are that the confirmation link was already visited, either
          # by some automation or by the user themselves, so we redirect without
          # a warning message.
          case socket.assigns do
            %{current_user: %{confirmed_at: confirmed_at}} when not is_nil(confirmed_at) ->
              {:noreply,
               socket
               |> put_flash(:error, "Account has already been confirmed")
               |> redirect(to: Routes.auth_login_path(socket, :login))}

            %{} ->
              {:noreply,
               socket
               |> put_flash(:error, "Account confirmation link is invalid or it has expired.")
               |> redirect(to: Routes.auth_login_path(socket, :login))}
          end
      end
    end
  end
end

lib/snownix_web/live/auth_live/forgot_password.ex
defmodule SnownixWeb.AuthLive.ForgotPassword do
  use SnownixWeb, :live_view

  alias Snownix.Accounts

  def mount(_, _, socket) do
    {
      :ok,
      socket
      |> assign(:page_title, gettext("Forgot Password"))
      |> assign(
        :changeset,
        Accounts.user_email_changeset(%Accounts.User{})
      )
    }
  end

  def handle_event("validate", %{"user" => user_params}, socket) do
    changeset =
      %Accounts.User{}
      |> Accounts.user_email_changeset(user_params)
      |> Map.put(:action, :validate)

    {:noreply, socket |> assign(:changeset, changeset)}
  end

  def handle_event("update", %{"user" => user_params}, socket) do
    %{"email" => email} = user_params

    if user = Accounts.get_user_by_email(email) do
      Accounts.deliver_user_reset_password_instructions(
        user,
        &Routes.auth_reset_password_url(socket, :reset, &1)
      )
    end

    {:noreply,
     socket
     |> put_flash(
       :info,
       gettext(
         "If your email is in our system, you will receive instructions to reset your password shortly."
       )
     )
     |> redirect(to: Routes.auth_login_path(socket, :login))}
  end
end

lib/snownix_web/live/auth_live/login.ex
defmodule SnownixWeb.AuthLive.Login do
  use SnownixWeb, :live_view

  alias Snownix.Accounts
  alias Snownix.Providers.Github

  def mount(_, _, socket) do
    {:ok,
     socket
     |> assign(:trigger_submit, false)
     |> assign(:changeset, Accounts.user_login_changeset(%Accounts.User{}))
     |> assign(:page_title, gettext("Sign in"))}
  end

  def handle_event("validate", %{"user" => user_params}, socket) do
    changeset =
      %Accounts.User{}
      |> Accounts.user_login_changeset(user_params)
      |> Map.put(:action, :validate)

    {:noreply, socket |> clear_flash() |> assign(:changeset, changeset)}
  end

  def handle_event("create", %{"user" => user_params}, socket) do
    %{"email" => email, "password" => password} = user_params

    if user = Accounts.get_user_by_email_and_password(email, password) do
      {:noreply,
       socket
       |> put_flash(:info, gettext("Welcome back %{username}!", username: user.username))
       |> assign(:trigger_submit, true)}
    else
      {:noreply,
       socket
       # In order to prevent user enumeration attacks, don't disclose whether the email is registered.
       |> put_flash(:error, gettext("Invalid email or password"))}
    end
  end
end

lib/snownix_web/live/auth_live/reconfirm.ex
defmodule SnownixWeb.AuthLive.Reconfirm do
  use SnownixWeb, :live_view

  alias Snownix.Accounts

  def mount(_, _, socket) do
    {
      :ok,
      socket
      |> assign(:page_title, gettext("Resend Confirmation Instructions"))
      |> assign(
        :changeset,
        Accounts.user_email_changeset(%Accounts.User{})
      )
    }
  end

  def handle_event("validate", %{"user" => user_params}, socket) do
    changeset =
      %Accounts.User{}
      |> Accounts.user_email_changeset(user_params)
      |> Map.put(:action, :validate)

    {:noreply, socket |> assign(:changeset, changeset)}
  end

  def handle_event("update", %{"user" => user_params}, socket) do
    %{"email" => email} = user_params

    if user = Accounts.get_user_by_email(email) do
      Accounts.deliver_user_confirmation_instructions(
        user,
        &Routes.auth_confirm_url(socket, :confirm, &1)
      )
    end

    {:noreply,
     socket
     |> put_flash(
       :info,
       gettext(
         "If your email is in our system and it has not been confirmed yet, " <>
           "you will receive an email with instructions shortly"
       )
     )
     |> redirect(to: Routes.auth_login_path(socket, :login))}
  end
end

lib/snownix_web/live/auth_live/register.ex
defmodule SnownixWeb.AuthLive.Register do
  use SnownixWeb, :live_view

  alias Snownix.Accounts
  alias Snownix.Providers.Github

  def mount(_, _, socket) do
    {:ok,
     socket
     |> assign(:changeset, Accounts.user_register_changeset(%Accounts.User{}))
     |> assign(:page_title, gettext("Sign up"))}
  end

  def handle_event("validate", %{"user" => user_params}, socket) do
    changeset =
      %Accounts.User{}
      |> Accounts.user_register_changeset(user_params, uniq_email: false)
      |> Map.put(:action, :validate)

    {:noreply, socket |> assign(:changeset, changeset)}
  end

  def handle_event("create", %{"user" => user_params}, socket) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.auth_confirm_url(socket, :confirm, &1)
          )

        {:noreply,
         socket
         |> put_flash(
           :info,
           gettext(
             "Registration completed successfully. please check your email to verify your account."
           )
         )
         |> redirect(to: Routes.auth_login_path(socket, :login))}

      {:error, changeset} ->
        {:noreply,
         socket
         |> assign(:changeset, changeset)}
    end
  end
end

lib/snownix_web/live/auth_live/reset_password.ex
defmodule SnownixWeb.AuthLive.ResetPassword do
  use SnownixWeb, :live_view

  alias Snownix.Accounts

  def mount(%{"token" => token}, _, socket) do
    {
      :ok,
      socket
      |> assign(:page_title, gettext("Reset Password"))
      |> get_user_by_reset_password_token(token)
    }
  end

  defp get_user_by_reset_password_token(socket, token) do
    if user = Accounts.get_user_by_reset_password_token(token) do
      socket
      |> assign(:user, user)
      |> assign(:token, token)
      |> assign(:changeset, Accounts.user_password_changeset(%Accounts.User{}))
    else
      socket
      |> put_flash(:error, "Reset password link is invalid or it has expired.")
      |> redirect(to: Routes.auth_login_path(socket, :login))
    end
  end

  def handle_event("validate", %{"user" => user_params}, socket) do
    changeset =
      %Accounts.User{}
      |> Accounts.user_password_with_email_changeset(user_params)
      |> Map.put(:action, :validate)

    {:noreply, socket |> assign(:changeset, changeset)}
  end

  def handle_event("update", %{"user" => user_params}, socket) do
    with %{"email" => email} <- user_params do
      if socket.assigns.user.email === email do
        case Accounts.reset_user_password(socket.assigns.user, user_params) do
          {:ok, _} ->
            {:noreply,
             socket
             |> put_flash(:info, "Password reset successfully.")
             |> redirect(to: Routes.auth_login_path(socket, :login))}

          {:error, changeset} ->
            {:noreply,
             socket
             |> assign(changeset: changeset)}
        end
      else
        {:noreply, socket |> put_flash(:error, gettext("Wrong information"))}
      end
    end
  end
end

lib/snownix_web/live/post_live/components/post_grid_component.ex
defmodule SnownixWeb.PostLive.Components.PostGridComponent do
  use SnownixWeb, :live_component
end

lib/snownix_web/live/post_live/index.html.heex
<h1>Listing Posts</h1>

<%= if @live_action in [:new, :edit] do %>
  <.modal return_to={Routes.post_index_path(@socket, :index)}>
    <.live_component
      module={SnownixWeb.PostLive.Components.FormComponent}
      id={@post.id || :new}
      title={@page_title}
      action={@live_action}
      post={@post}
      return_to={Routes.post_index_path(@socket, :index)}
    />
  </.modal>
<% end %>

<table>
  <thead>
    <tr>
      <th>Poster</th>
      <th>Slug</th>
      <th>Title</th>
      <th>Description</th>
      <th>Published at</th>

      <th></th>
    </tr>
  </thead>
  <tbody id="posts">
    <%= for post <- @posts do %>
      <tr id={"post-#{post.id}"}>
        <td><img src={get_post_poster(post, :thumb)}></td>
        <td><%= post.slug %></td>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= post.published_at %></td>

        <td>
          <span><%= live_redirect "Show", to: Routes.post_show_path(@socket, :show, post) %></span>
          <span><%= live_patch "Edit", to: Routes.post_index_path(@socket, :edit, post) %></span>
          <span><%= link "Delete", to: "#", phx_click: "delete", phx_value_id: post.id, data: [confirm: "Are you sure?"] %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<span><%= live_patch "New Post", to: Routes.post_index_path(@socket, :new) %></span>

lib/snownix_web/live/post_live/list.html.heex
<.live_component module={SnownixWeb.SharedLive.AlertsComponent} flash={@flash} id="index-alerts" />
<section id="posts" class="py-4 max-w-7xl" phx-hook="ScrollOnUpdate">
  <div class="grid grid-cols-1 gap-12 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3">
    <%= for post <- @pagination.items do %>
      <.live_component module={SnownixWeb.PostLive.Components.PostGridComponent} post={post} id={"post-#{post.id}"} />
    <% end %>
  </div>


  <%= if !(@pagination.page <= 1 && !@pagination.has_next) do %>
  <div class="flex flex-col items-center justify-center mt-20 space-x-0 space-y-2 md:space-x-2 md:space-y-0 md:flex-row">
    <button 
    disabled={!@pagination.has_prev} 
    phx-value-page={@pagination.prev_page}
    phx-click="page" 
    class="w-full rounded-full btn btn-light btn-xl md:w-auto">
        Prev Page
    </button>
    
    <div class="flex space-x-2">
      <button class="btn" disabled><%= @pagination.page %>/<%= @pagination.total %></button>
    </div>

    <button 
    disabled={!@pagination.has_next} 
    phx-value-page={@pagination.next_page}
    phx-click="page"
    class="w-full rounded-full btn btn-light btn-xl md:w-auto">
        Next Page
    </button>
  </div>
  <% end %>
</section>

lib/snownix_web/live/post_live/read.html.heex
<div class="post__read px-4 py-4 md:py-14 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-lg md:px-24 lg:px-8 space-y-12 ">
  <%# Hero %>
  <div class="md:mx-auto sm:text-center lg:max-w-4xl space-y-6 md:space-y-4">
    <h2
      class=" font-sans text-xl md:text-3xl font-bold leading-none tracking-tight text-gray-900 sm:text-4xl md:mx-auto">
      <span class="hidden relative md:inline-block">
        <svg viewBox="0 0 52 24" fill="currentColor"
          class="absolute top-0 left-0 z-0 hidden w-32 -mt-8 -ml-20 text-blue-gray-100 lg:w-32 lg:-ml-28 lg:-mt-10 sm:block">
          <defs>
            <pattern id="679d5905-e08c-4b91-a66c-84aefbb9d2f5" x="0" y="0" width=".135" height=".30">
              <circle cx="1" cy="1" r="0.7"></circle>
            </pattern>
          </defs>
          <rect fill="url(#679d5905-e08c-4b91-a66c-84aefbb9d2f5)" width="52" height="24"></rect>
        </svg>
      </span>
      <%= @post.title %>
    </h2>
    <p class="text-base text-gray-700 md:text-lg">
      <%= @post.description %>
    </p>
    
    <%= if length(@post.categories) do %>
        <div class="post__categories">
        <%= for category <- @post.categories do %>
            <a class="post__category">
                <%= category.title %>
            </a>
        <% end %>
        </div>
    <% end %>
  </div>
  <%# Poster %>
  <div class="flex flex-col items-center mx-auto space-y-14 lg:max-w-4xl">
    <%= if @post.poster do %>
      <div class="w-full transition-shadow duration-300 hover:shadow-xl">
        <img class=" object-fill w-full h-56 rounded-xl shadow-sm sm:h-64 md:h-80 lg:h-auto" src={get_post_poster(@post, :original)} alt={@post.title} />
      </div>
    <% end %>
  <%# Author & Info %>
    <div class="flex flex-wrap justify-center space-x-2 items-center text-md text-dark">
      <%= if @post.author do %>
        <%= live_redirect to: Routes.account_profile_path(@socket, :index, @post.author.username) do %>
          <div class="flex justify-center space-x-2 items-center">
            <img alt={@post.author.username <> " Avatar"} class="avatar border rounded-full" width="40px" height="40px" src={get_user_avatar(@post.author)}>
            <h4 class="font-medium">
              <%= @post.author.fullname || @post.author.username %>
            </h4>
          </div>
        <% end %>
        <div>·</div>
      <% end %>
        <div class="flex justify-center space-x-2 items-center">
          <time datetime={@post.published_at}><%= article_date_format(@post.published_at) %></time>
        </div>
        <div>·</div>
        <div class="flex justify-center space-x-1 items-center">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor" >
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
          </svg>
          <span><%= @post.read_time %> min read</span>
        </div>
      <%= if @current_user && @post.author_id == @current_user.id do %>
        <div>·</div>
        <button data-menu data-hover >
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 hover:text-primary" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 5v.01M12 12v.01M12 19v.01M12 6a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z" />
          </svg>
          <ul data-menu-dropdown class=" px-2 list-none bg-white shadow left-6 top-6">
            <li class="p-3 hover:text-primary" >
              <%= live_redirect to: Routes.post_edit_path(@socket, :edit, @post.id) do %>
                Edit
              <% end %>
            </li>
            <li class="p-3 hover:text-primary" phx-click="delete">
              Delete
            </li>
          </ul>
        </button>
      <% end %>
    </div>

  </div>
  <%# Entities %>
  <div class="flex flex-col md:mx-auto  prose space-y-8 lg:max-w-4xl">
    <%= for entity <- @post.entities do %>
      <.live_component 
        id={entity.id}
        entity={entity}
        module={SnownixWeb.PostLive.Components.EntityComponent} />
    <% end %>
  </div>
</div>

lib/snownix_web/live/post_live/show.html.heex
<h1>Show Post</h1>

<%= if @live_action in [:edit] do %>
  <.modal return_to={Routes.post_show_path(@socket, :show, @post)}>
    <.live_component
      module={SnownixWeb.PostLive.FormComponent}
      id={@post.id}
      title={@page_title}
      action={@live_action}
      post={@post}
      return_to={Routes.post_show_path(@socket, :show, @post)}
    />
  </.modal>
<% end %>

<ul>

  <li>
    <strong>Slug:</strong>
    <%= @post.slug %>
  </li>

  <li>
    <strong>Title:</strong>
    <%= @post.title %>
  </li>

  <li>
    <strong>Poster:</strong>
    <%= get_post_poster(@post, :thumb) %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @post.description %>
  </li>

  <li>
    <strong>Published at:</strong>
    <%= @post.published_at %>
  </li>

</ul>

<span><%= live_patch "Edit", to: Routes.post_show_path(@socket, :edit, @post), class: "button" %></span> |
<span><%= live_redirect "Back", to: Routes.post_index_path(@socket, :index) %></span>